### ISSUE TITLE
[BACK] Filtragem de usuários por cargo

### ISSUE THREAD

**Issue by MariaGabrielaReis** [The-Bugger-Ducks/help-duck-register#17]

**Comment by ThHenrique** [comment]
### Salve salve camaradas, excelente semana pra você que está lendo 🙌 

#17 - Implementado filtro de usuário por cargo e também pelo nome de usuário;

### Mas como funciona essa belezinha ? vem comigo..

#### Para realizar esses filtros basta utilizar o endpoint abaixo:

```URI:  <URL-REGISTER>/users/search```

#### Agora que vem o chan

### Para realizar filtro por cargo (role), basta passar o parâmetro abaixo na requisição:

- Filtro por administradores
```URI:  <URL-REGISTER>/users/search?role=admin```

- Filtro por suporte
```URI:  <URL-REGISTER>/users/search?role=support```

- Filtro por clientes
```URI:  <URL-REGISTER>/users/search?role=client```

---

#### Mas e se quisermos filtrar por nome de usuário ?

### Basta adicionar o parâmetro username:

- Essa busca é feita tanto por nome como sobrenome 😄 

```URI:  <URL-REGISTER>/users/search?username=nomedousuário```

#### MAAAAS, e se eu quiser filtrar os dois ? Da também HEHE

- Basta passar os dois parâmetros separados por um E comercial (&):

```URI:  <URL-REGISTER>/users/search?role=admin&username=teste```

- A ordem tanto faz (role primeiro, como por último 🤷‍♂️), mas a sintaxe é separar o parâmetros pelo &
